// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.4
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// CONFIG_BUS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : reserved
// 0x14 : Data signal of block_address
//        bit 31~0 - block_address[31:0] (Read/Write)
// 0x18 : reserved
// 0x1c : Data signal of input_addr
//        bit 31~0 - input_addr[31:0] (Read/Write)
// 0x20 : reserved
// 0x24 : Data signal of weights_addr
//        bit 31~0 - weights_addr[31:0] (Read/Write)
// 0x28 : reserved
// 0x2c : Data signal of output_addr
//        bit 31~0 - output_addr[31:0] (Read/Write)
// 0x30 : reserved
// 0x34 : Data signal of inputSize
//        bit 31~0 - inputSize[31:0] (Read/Write)
// 0x38 : reserved
// 0x3c : Data signal of outputSize
//        bit 31~0 - outputSize[31:0] (Read/Write)
// 0x40 : reserved
// 0x44 : Data signal of inputDepth
//        bit 31~0 - inputDepth[31:0] (Read/Write)
// 0x48 : reserved
// 0x4C : Data signal of outRowStart
//        bit 31~0 - outRowStart[31:0] (Read/Write)
// 0x50 : reserved
// 0x54 : Data signal of outRowEnd
//        bit 31~0 - outRowEnd[31:0] (Read/Write)
// 0x58 : reserved
// 0x5C : Data signal of outColStart
//        bit 31~0 - outColStart[31:0] (Read/Write)
// 0x60 : reserved
// 0x64 : Data signal of outColEnd
//        bit 31~0 - outColEnd[31:0] (Read/Write)
// 0x68 : reserved
// 0x6C : Data signal of outDepthStart
//        bit 31~0 - outDepthStart[31:0] (Read/Write)
// 0x70 : reserved
// 0x74 : Data signal of outDepthEnd
//        bit 31~0 - outDepthEnd[31:0] (Read/Write)
// 0x78 : reserved
// 0x7C : Data signal of inDepthStart
//        bit 31~0 - inDepthStart[31:0] (Read/Write)
// 0x80 : reserved
// 0x84 : Data signal of inDepthEnd
//        bit 31~0 - inDepthEnd[31:0] (Read/Write)
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_ADDR_AP_CTRL               0x00
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_ADDR_GIE                   0x04
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_ADDR_IER                   0x08
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_ADDR_ISR                   0x0c
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_ADDR_BLOCK_ADDRESS_DATA    0x14
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_BITS_BLOCK_ADDRESS_DATA    32
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_ADDR_INPUT_ADDR_DATA 	 0x1c
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_BITS_INPUT_ADDR_DATA 	 32
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_ADDR_WEIGHTS_ADDR_DATA  	 0x24
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_BITS_WEIGHTS_ADDR_DATA  	 32
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_ADDR_OUTPUT_ADDR_DATA      0x2c
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_BITS_OUTPUT_ADDR_DATA      32
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_ADDR_INPUT_SIZE_DATA    	 0x34
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_BITS_INPUT_SIZE_DATA	 32
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_ADDR_OUTPUT_SIZE_DATA      0x3c
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_BITS_OUTPUT_SIZE_DATA      32
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_ADDR_INPUT_DEPTH_DATA      0x44
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_BITS_INPUT_DEPTH__DATA     32
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_ADDR_OUT_ROW_START_DATA    0x4c
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_BITS_OUT_ROW_START_DATA    32
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_ADDR_OUT_ROW_END_DATA      0x54
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_BITS_OUT_ROW_END_DATA      32
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_ADDR_OUT_COL_START_DATA    0x5c
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_BITS_OUT_COL_START_DATA    32
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_ADDR_OUT_COL_END_DATA      0x64
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_BITS_OUT_COL_END_DATA      32
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_ADDR_OUT_DEPTH_START_DATA  0x6c
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_BITS_OUT_DEPTH_START_DATA  32
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_ADDR_OUT_DEPTH_END_DATA    0x74
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_BITS_OUT_DEPTH_END_DATA    32
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_ADDR_IN_DEPTH_START_DATA   0x7c
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_BITS_IN_DEPTH_START_DATA   32
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_ADDR_IN_DEPTH_END_DATA     0x84
#define XLLOYDS_KERNEL_TOP_CONFIG_BUS_BITS_IN_DEPTH_END_DATA     32


